/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Executes the creation of the shell in the pseudoconsole create previously with conpty_create_process.
 * The process is created in a suspended state to allow for the start of the worker sockets.
 *
 * The connection object containing the required values of process id and thread id.
 */
export declare function conptyConnect(ptyId: number, cmdline: string, cwd: string, env: Record<string, string>, onexit: (arg0: number, arg1: number) => void): IConptyConnection

/**
 * This function creates the pseudoconsole and the named pipes for input and output.
 *
 * Returns the created process information.
 */
export declare function conptyCreateProcess(cols: number, rows: number, pipeName: string, conptyInheritCursor: boolean): IConptyProcess

/**
 * This method executes the kill operation on a valid console handle.
 * Closing the pseudoconsole and the input/output handles attached.
 */
export declare function conptyKill(ptyId: number): void

/** This method executes the resize operation on a valid console handle. */
export declare function conptyResize(ptyId: number, cols: number, rows: number): void

/**
 * Start the suspended process previously created with conpty_create_process and contpy_connect.
 *
 * Returns the result of the operation.
 */
export declare function conptyStartProcess(process: number): number

export declare function getConsoleProcessList(pid: number): Array<number>

export interface IConptyConnection {
  pid: number
  tid: number
}

export interface IConptyProcess {
  fd: number
  pty: number
  conin: string
  conout: string
}

export interface IUnixOpenProcess {
  master: number
  slave: number
  pty: string
}

export interface IUnixProcess {
  fd: number
  pid: number
  pty: string
}

export interface IWinptyProcess {
  pty: number
  fd: number
  conin: string
  conout: string
  pid: number
  innerPid: number
  innerPidHandle: number
}

export declare function ptyFork(file: string, args: Array<string>, env: Record<string, string>, cwd: string, cols: number, rows: number, uid: number, gid: number, utf8: boolean, onexit: (arg0: number, arg1: number) => void): IUnixProcess

export declare function ptyOpen(cols: number, rows: number): IUnixOpenProcess

/** Gets the name of the process with the given file descriptor */
export declare function ptyProcess(fd: number, tty: string): string | null

/**
 * Resizes the terminal pointed to by the provided file descriptor
 * to the preferred
 */
export declare function ptyResize(fd: number, cols: number, rows: number): void

/**
 * Bakes the version number into the binary so that it can be detected
 * if the binary version is not up to date with the library version
 */
export declare function version(): string

export declare function winptyGetExitCode(innerPidHandle: number): number

export declare function winptyGetProcessList(pid: number): Array<number>

export declare function winptyKill(pid: number, innerPidHandle: number): void

export declare function winptyResize(pid: number, cols: number, rows: number): void

export declare function winptyStartProcess(file: string, commandLine: string, env: Record<string, string>, cwd: string, cols: number, rows: number, debug: boolean): IWinptyProcess
