name: 'Build Windows'

on:
  workflow_call:

jobs:
  build-windows-x86_64:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      
    - name: Set Node.js lts
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Verify Node.js installation
      run: node --version
    
    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install
    
    - name: Build for platform
      run: yarn build
    
    - name: Test for platform
      run: yarn test

    - name: list files
      run: ls -la

    - name: upload windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-x86_64
        path: ${{ github.workspace }}/native/node-pty.win32-x64-msvc.node
        if-no-files-found: error
  
  build-windows-arm64:
    runs-on: windows-latest-arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      
    - name: Set Node.js lts
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Verify Node.js installation
      run: node --version
    
    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install
    
    - name: Build for platform
      run: yarn build
    
    - name: Test for platform
      run: yarn test

    - name: list files
      run: ls -la

    - name: upload windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-arm64
        path: ${{ github.workspace }}/native/node-pty.arm64-msvc.node
        if-no-files-found: error