name: 'Build and test Linux'

on:
  workflow_call:

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set Node.js lts
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Verify Node.js installation
      run: node --version
    
    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install
    
    - name: Build for platform
      run: yarn build

    - name: Test for platform
      run: yarn test
    
    - name: upload linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-x86_64
        path: ${{ github.workspace }}/native/node-pty.linux-x64-gnu.node
        if-no-files-found: error
  
  build-linux-arm64:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set Node.js lts
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Verify Node.js installation
      run: node --version
    
    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install
    
    - name: Build for platform
      run: yarn build
    
    - name: Test for platform
      run: yarn test
    
    - name: list files
      run: ls -la
    
    - name: upload linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-arm64
        path: ${{ github.workspace }}/native/node-pty.linux-arm64-gnu.node
        if-no-files-found: error